# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessEmployee.ui'
#
# Created: Wed Dec 05 13:50:36 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.setEnabled(True)
        Dialog.resize(1300, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Qt/4.8.6/examples/declarative/shadereffects/qml/shadereffects/images/sky.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 180, 391, 311))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidgetResult = QtGui.QTableWidget(Dialog)
        self.tableWidgetResult.setGeometry(QtCore.QRect(410, 80, 461, 411))
        self.tableWidgetResult.setObjectName(_fromUtf8("tableWidgetResult"))
        self.tableWidgetResult.setColumnCount(0)
        self.tableWidgetResult.setRowCount(0)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButtonSearch = QtGui.QPushButton(Dialog)
        self.pushButtonSearch.setGeometry(QtCore.QRect(640, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setObjectName(_fromUtf8("pushButtonSearch"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1080, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButtonClear = QtGui.QPushButton(Dialog)
        self.pushButtonClear.setGeometry(QtCore.QRect(1190, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.treeWidget = QtGui.QTreeWidget(Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(1120, 50, 171, 441))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.comboBoxType = QtGui.QComboBox(Dialog)
        self.comboBoxType.setGeometry(QtCore.QRect(900, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(14)
        self.comboBoxType.setFont(font)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.lineEditKey = QtGui.QLineEdit(Dialog)
        self.lineEditKey.setGeometry(QtCore.QRect(100, 10, 501, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(14)
        self.lineEditKey.setFont(font)
        self.lineEditKey.setObjectName(_fromUtf8("lineEditKey"))
        self.tableWidgetResultDst = QtGui.QTableWidget(Dialog)
        self.tableWidgetResultDst.setGeometry(QtCore.QRect(880, 80, 231, 411))
        self.tableWidgetResultDst.setObjectName(_fromUtf8("tableWidgetResultDst"))
        self.tableWidgetResultDst.setColumnCount(0)
        self.tableWidgetResultDst.setRowCount(0)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(410, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(880, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButtonResultDstOut = QtGui.QPushButton(Dialog)
        self.pushButtonResultDstOut.setGeometry(QtCore.QRect(1010, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(14)
        self.pushButtonResultDstOut.setFont(font)
        self.pushButtonResultDstOut.setObjectName(_fromUtf8("pushButtonResultDstOut"))
        self.pushButtonResultOut = QtGui.QPushButton(Dialog)
        self.pushButtonResultOut.setGeometry(QtCore.QRect(770, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(14)
        self.pushButtonResultOut.setFont(font)
        self.pushButtonResultOut.setObjectName(_fromUtf8("pushButtonResultOut"))
        self.spinBoxSrc = QtGui.QSpinBox(Dialog)
        self.spinBoxSrc.setGeometry(QtCore.QRect(130, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        self.spinBoxSrc.setFont(font)
        self.spinBoxSrc.setObjectName(_fromUtf8("spinBoxSrc"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(230, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spinBoxStart = QtGui.QSpinBox(Dialog)
        self.spinBoxStart.setGeometry(QtCore.QRect(350, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        self.spinBoxStart.setFont(font)
        self.spinBoxStart.setObjectName(_fromUtf8("spinBoxStart"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditColumArray = QtGui.QLineEdit(Dialog)
        self.lineEditColumArray.setGeometry(QtCore.QRect(10, 110, 391, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditColumArray.setFont(font)
        self.lineEditColumArray.setText(_fromUtf8(""))
        self.lineEditColumArray.setObjectName(_fromUtf8("lineEditColumArray"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "文件分析", None))
        self.label.setText(_translate("Dialog", "关键字：", None))
        self.pushButtonSearch.setText(_translate("Dialog", "开始检索", None))
        self.pushButton.setText(_translate("Dialog", "打开文件", None))
        self.pushButtonClear.setText(_translate("Dialog", "清空文件", None))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "文件列表", None))
        self.comboBoxType.setItemText(0, _translate("Dialog", "商品关键词效果", None))
        self.comboBoxType.setItemText(1, _translate("Dialog", "无线三级商品模式", None))
        self.comboBoxType.setItemText(2, _translate("Dialog", "自定义搜索", None))
        self.label_2.setText(_translate("Dialog", "词根所在列:", None))
        self.label_3.setText(_translate("Dialog", "目标数据：", None))
        self.label_4.setText(_translate("Dialog", "结果统计：", None))
        self.pushButtonResultDstOut.setText(_translate("Dialog", "导出", None))
        self.pushButtonResultOut.setText(_translate("Dialog", "导出", None))
        self.label_5.setText(_translate("Dialog", "原始数据：", None))
        self.label_6.setText(_translate("Dialog", "开始检索行：", None))
        self.label_7.setText(_translate("Dialog", "检索列（；分割）：", None))

